server:
  port: 10002

spring:
  application:
    name: zipkin-receiver
  zipkin:
    base-url: http://127.0.0.1:9411

#============== kafka ===================
kafka:
  consumer:
    zookeeper.connect: 192.168.7.128:2181
    servers: 192.168.7.128:9092
    enable.auto.commit: true
    session.timeout: 6000
    auto.commit.interval: 100
    auto.offset.reset: latest
    topic: test
    group.id: test
    concurrency: 10
