server:
  port: 10001

spring:
  application:
    name: zipkin-sender
  zipkin:
    base-url: http://127.0.0.1:9411


#============== kafka ===================
kafka:
  producer:
    servers: 192.168.7.128:9092
    retries: 0
    batch.size: 4096
    linger: 1
    buffer.memory: 40960
