spring:
    application:
        name: sharding-jdbc-demo
    datasource:
            initialize: false
server:
    port: 8099

#----eureka 配置
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

default.count.limit: 100
default.money.limit: 1000
default.expire.sec: 600
max.dist.sec: 1800

#----mybatis配置
mybatis.configuration.map-underscore-to-camel-case: true